[package]
name = "opencc_jieba_pyo3"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "opencc_jieba_pyo3"
crate-type = ["cdylib"]

[dependencies]
#pyo3 = { version = "0.25.0", features = ["extension-module", "abi3-py38"]}
pyo3 = "0.25.0"
opencc-jieba-rs = { path = "../opencc-jieba-rs" }
