class OpenCC:
    def __init__(self, config: str) -> None:
        self.config = config
        ...

    def convert(self, input: str, punctuation: bool) -> str:
        ...

    def zho_check(self, input: str) -> int:
        ...

    def jieba_cut(self, input_text: str) -> list[str]:
        ...

    def jieba_cut_and_join(self, input_text: str, delimiter: str = "/") -> str:
        ...

    def jieba_keyword_extract_textrank(self, input_text: str, top_k: int) -> list[str]:
        ...

    def jieba_keyword_extract_tfidf(self, input_text: str, top_k: int) -> list[str]:
        ...
    def jieba_keyword_weight_textrank(self, input_text: str, top_k: int) -> list[tuple[str, float]]:
        ...

    def jieba_keyword_weight_tfidf(self, input_text: str, top_k: int) -> list[tuple[str, float]]:
        ...